### ISSUE TITLE
Long workflows result in extremely high data transfer load

### ISSUE THREAD

**Issue by mchl-hess** [Outset-AI/dramatiq-workflow#1]
The entire workflow graph is updated and stored with every chained/grouped task in the queue. This scales exponentially which causes significant slowdowns for very large workflows.

**Comment by pencil** [comment]
This has been addressed by several optimizations and a note in the README in 0.2.0.

A future optimization could be to store the metadata of messages in a separate store (e.g. DynamoDB) to further reduce the size of the queue.
